### ISSUE TITLE
ditch markdown headers

### ISSUE THREAD

**Issue by rehandalal** [mozilla/standup#110]
So an update like this:
`#mfbt in Toronto`

Gets converted into:
`<h1>mfbt in Toronto</h1>`

Not sure if we can partially implement markdown to only support certain features we want, since we probably don't need headlines and stuff. Plus we can prevent @ednapiranha from spamming the main feed with images.

**Comment by willkg** [comment]
I adjusted the title of this to just cover the header problem. It's interesting to think about ditching markdown altogether, but we're increasing the prominence of using the web form for entering statuses and I've heard some people really like multi-paragraph statuses and given that, it's probably easier to just stick with Markdown for now.

Given that we're done here, I'm closing this out.
