### ISSUE TITLE
Include url when replying to statuses 

### ISSUE THREAD

**Issue by tarasglek** [mozilla/standup#147]
teamstat UX is nicer
14:06 <@taras> status: blogging
14:06 < status> taras: status recorded at http://teamstat.us/#show/irc.mozilla.org/perf/taras/67471

vs
14:31 <@taras> rogerroger: hi
14:31 < rogerroger> Ok, submitted status #5521.

**Comment by pmac** [comment]
I'm going to close this since:

1. The bot now does output a URL, though it's for the user's page, not for the new status
2. Further discussion should be had at the [bot repo](https://github.com/mozilla/standup-irc/)

Please file a new issue or reopen if further discussion is needed.
