### ISSUE TITLE
search

### ISSUE THREAD

**Issue by willkg** [mozilla/standup#164]
It'd be nice to be able to search for bug numbers, pull requests, tags or specific text and have it show all the relevant status reports.

**Comment by a2sheppy** [comment]
Yeah, this would be a big help in finding all the status updates related to a given bug, for instance, which would be helpful when writing project wrap-up reports and the like.

**Comment by willkg** [comment]
I want this, too. I'll try to work on it in the next month. It's not super hard. It'd be cool to re-use the query parser I wrote for Input.

https://github.com/mozilla/fjord/commit/1ea8a6e72e57bf56be3ff2a1875111e636d2ac28

Pretty sure that'll give us a framework to write a good search syntax which has it's UX ughs, but maybe someone better can throw a nice UI/UX on top of it.

**Comment by willkg** [comment]
Django 1.10 and Postgres allow for full-text search which is going to be more powerful than what I'm going to build in this iteration. It's something we should think about if there are needed use cases which don't work with the search I'm building.

https://docs.djangoproject.com/en/1.10/ref/contrib/postgres/search/

**Comment by a2sheppy** [comment]
Excellent — let me know if you can use help with testing or anything like that.

**Comment by willkg** [comment]
I threw together a "good enough first implementation" in #346. It handles tags and users and anything in the content. It's not a "search" so much as it's a "filter" in this current iteration. Namely it doesn't do stemming, only does exact matches and doesn't return a "search score".

I think we should go with this for a bit and see how it goes. It definitely doesn't handle all possible use cases, but maybe it's good enough for now. Doing more than this requires either a real search engine (for example Elasticsearch) and/or using the postgres fanciness in Django 1.10 or something along those lines. It's definitely a lot more work.

I wrote this such that I can throw an API in front of it trivially. I'll probably do that soon.
