### ISSUE TITLE
Enable HTTPS

### ISSUE THREAD

**Issue by mozfreddyb** [mozilla/standup#168]
There are [great docs on how to deploy HTTPS](https://timtaubert.de/blog/2014/10/deploying-tls-the-hard-way/) and I am willing to help and do _all_ the things. :-)

Opinions?

**Comment by pmac** [comment]
We just need a cert. We're rewriting standup now, and will hopefully roll out HTTPS with the new version soon. I've filed [bug 1300770](https://bugzilla.mozilla.org/show_bug.cgi?id=1300770) to request the cert. We'll use [Heroku's new free SSL offering](https://devcenter.heroku.com/articles/ssl-beta).

**Comment by pmac** [comment]
Still just waiting for the cert. I don't think this should block our roll-out of the new site though.

**Comment by pmac** [comment]
I have the cert! Will install after we close #228

**Comment by pmac** [comment]
Done! WOO!

**Comment by willkg** [comment]
Yay!
