### ISSUE TITLE
Replace Persona authentication with something else

### ISSUE THREAD

**Issue by globau** [mozilla/standup#170]
Persona is being turned off on Nov 30th; standup needs to migrate to a different auth system.

See https://mana.mozilla.org/wiki/display/Identity/Persona+migration+guide+for+internal+sites in particular the "Migration options for internal Mozilla sites" section.

**Comment by willkg** [comment]
Thank you for the heads up!

However, this project is pretty dead, so unless someone shows up to take over, I think this will just sit around.

**Comment by gene1wood** [comment]
I've opened this ticket to track potential decom of the site : https://bugzilla.mozilla.org/show_bug.cgi?id=1287965

**Comment by willkg** [comment]
Standup v2 is using Persona and GitHub auth at the moment. In the very near future, we're going to nix Persona.

Given that, I'm closing this out.
