### ISSUE TITLE
STANDUP IS NO LONGER MAINTAINED

### ISSUE THREAD

**Issue by willkg** [mozilla/standup#171]
This project is no longer maintained. If you're interested in taking over, please leave a comment here.

**Comment by armenzg** [comment]
Hi @willkg are there other alternatives to this project?

Has anyone shown interest on taking over?

Thanks

**Comment by willkg** [comment]
No one has approached me with a plan to take over. Beyond that, I don't know.

I don't know what alternatives there are.

If someone wants to do some research and make a list of alternatives and write that list down as a comment in this issue, that'd probably be helpful for anyone who's still using standup.

**Comment by armenzg** [comment]
Thanks for the info!
Was there a mailing list used to announce the decision of making the tool unmaintained? If so I would like to drive some conversation there.

**Comment by mythmon** [comment]
This Github repo and issue tracker is the place the announcement was made. This issue is the announcement.

**Comment by willkg** [comment]
There is no mailing list that I'm aware of. There is a dead IRC channel (#standup) and a dead issue tracker (this one).

There wasn't an explicit decision to stop maintenance. Those of us who worked on this project no longer use it and wandered off to do other things and no one expressed interest as far as I'm aware to take over. It's been this way for a year or more. The only thing that happened on May 24th was that I wrote up an issue denoting as such and modified the README.

If you're interested in communicating with the other users, I suggest looking at the website to see who's using it and contacting them.

**Comment by armenzg** [comment]
Good idea!
Thank you for clarifying it.

On 6 July 2016 at 12:59, Will Kahn-Greene <notifications@github.com> wrote:

> There is no mailing list that I'm aware of. There is a dead IRC channel
> (#standup) and a dead issue tracker (this one).
>
> There wasn't an explicit decision to stop maintenance. Those of us who
> worked on this project no longer use it and wandered off to do other things
> and no one expressed interest as far as I'm aware to take over. It's been
> this way for a year or more. The only thing that happened on May 24th was
> that I wrote up an issue denoting as such and modified the README.
>
> If you're interested in communicating with the other users, I suggest
> looking at the website to see who's using it and contacting them.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/mozilla/standup/issues/171#issuecomment-230836991>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AACtemDfqTgDpDWUHqRrPz80m3rew2JZks5qS974gaJpZM4Ilr6v>
> .
>



-- 
Zambrano Gasparnian, Armen
Engineering productivity engineer - #ateam
http://armenzg.blogspot.ca

**Comment by willkg** [comment]
@pmac and I are rewriting standup and making some super sweet progress. Having said that, we haven't finished the rewrite and haven't replaced the existing standup, yet.

Once that happens (possibly by the end of September?), I'll update this issue with the status and what's going on and then close it out.

**Comment by willkg** [comment]
@pmac and I pushed out Standup v2 yesterday.

Given that, I'm going to close this out.
