### ISSUE TITLE
"make test" needs some tlc

### ISSUE THREAD

**Issue by willkg** [mozilla/standup#173]
Right now, running `make test` runs collectstatic and then runs the tests. collectstatic is required because it puts all the static files in the place where whitenoise can find them. This is needed because they're referred to in the templates.

Is there a way to run the tests without running collectstatic every time? Should we do some make-fu build dependency stuff to make that happen? Can we accurately figure out when we need to re-run collectstatic?

Further, if you want to run a single test, you have to emulate what `make test` does. I think this probably means we want to move the test execution into a bin/test.sh file which can pass along arguments and then have `make test` run that. I think that's what Erik suggested when I asked him about similar things with DXR.

Anyhow, this issue covers making `make test` experience better and more helpful for real-world development.

**Comment by pmac** [comment]
Reopening for further discussion, though it is potentially fixed.

**Comment by willkg** [comment]
The cumulative set of changes since I wrote this issue pretty much cover it. So I'm pretty ok with closing this out.
