### ISSUE TITLE
write db migration script

### ISSUE THREAD

**Issue by willkg** [mozilla/standup#178]
When we go to production with the new Standup, we're going to need to migrate the data from the old system to the new system.

I'm pretty sure the two systems don't share any table names. Maybe we can run `./manage.py migrate` which sets up all the Django tables and then run a script that copies all the data from the old tables to the new tables in the same database. Then later wipe out the old tables.

This issue covers figuring out how we want to do that, writing the relevant script, pulling a backup of the db locally and testing it all out.

**Comment by pmac** [comment]
I'm thinking we might be able to just set the table names in our new Django models and it may Just Work™️. So I'll be trying that as a way to close this one, and go with the data migration route if I fail.
