### ISSUE TITLE
implement github auth

### ISSUE THREAD

**Issue by willkg** [mozilla/standup#179]
@pmac and I looked through the relevant standup issues and talked to some people and then mulled over our options for auth now that Persona is going away. We settled on this set:

1. nopassword: the entire thing is email-driven
2. google auth
3. github auth

Seems non-trivial to get email set up for a variety of reasons. Further, with SUMO we constantly had problems with email not getting to the recipient and not having good ways to diagnose what happened. That was irritating as all hell. While I like the nopassword method in theory, I'm inclined to not do this because of the implementation and maintenance effort I think will be required.

I find google auth irritating. But it's an option.

Github auth seems the easiest of the three to implement and maintain, so I think we're going to go with this one for now. We're going to use django-allauth which MDN is using so we can expand into other social providers later if need be.

This issue covers implementing Github auth for the MVP for now.

**Comment by pmac** [comment]
I've evaluated both django-allauth and python-social-auth for this and feel that the latter is very much superior for our use case. python-social-auth is much more configurable, more customizable with its *pipelines* structure, and is only about social auth where allauth also deals a lot with local users and email verification and things we don't want or need. I recommend we move forward with it.

**Comment by jotes** [comment]
@pmac I noticed you mentioned standu.ps at the web-dev extravanza meeting. I'm a contributor and I work on migration from django-browserid to django-allauth for Pontoon. The only relatively minor problem I've encountered is a lack of support for the jinja2 tags.
I think you can look at:
https://github.com/mozilla/pontoon/pull/436/files
We currently support Persona and Firefox Accounts.

**Comment by pmac** [comment]
Thanks @jotes! We'd love to support FxA. How'd you make that happen? Just have to talk to the right people?

**Comment by jotes** [comment]
@pmac Yeah, I think you can request credentials at the dev-fxa channel for the staging environment and later you have to add a bug to bugzilla (like this one: https://bugzilla.mozilla.org/show_bug.cgi?id=1300044).
