### ISSUE TITLE
figure out how to migrate users from Persona to GitHub auth

### ISSUE THREAD

**Issue by willkg** [mozilla/standup#180]
After we implement Github auth and possibly as part of the migration script, we're going to need to figure out how to migrate users from Persona to Github auth.

This issue involves:

1. getting a backup of the db
2. analyzing the db to figure out what the situation is
3. figuring out a plan

As a side note, we should only be migrating users who have used Standup in the last x months.

**Comment by pmac** [comment]
We could potentially leave this to the users. If we started with support for both Persona and Github we could prompt those signed in but who don't have a github account associated to add one. This should catch most of the active users I think. After we remove Persona when it is shut down we could fall back to email matching or prompting users to file issues if they've lost access to their account. It's possible we could also match with the existing "github_handle" field, but that is in no way verified AFAIK, and thus could be a security issue.

**Comment by pmac** [comment]
So are we kinda done with this one? We've got that new login page, and if a user logs in using Persona they'll be annoyed with a banner at the top of every page asking them to add their Github account. I'm open to other suggestions, but I think we might be "good enough".

**Comment by willkg** [comment]
I think that covers everything. Yay team!
