### ISSUE TITLE
set up -stage environment

### ISSUE THREAD

**Issue by willkg** [mozilla/standup#187]
We need a -stage environment to help us feel confident everything is working as well as a place to test new development.

A -stage environment for standup has a couple of parts:

- [x] a -stage standup heroku app
- [x] a -stage standup-irc bot that points to the -stage standup heroku app

Then we have that bot sit in the `#standup` irc channel.

**Comment by pmac** [comment]
Phase 1 is complete and Travis is auto-deploying commits to `master` to the [stage app](https://standupstage.herokuapp.com/admin/).

**Comment by pmac** [comment]
stage IRC bot is deployed and configured. Nick is `standupstage`. Heroku app name is `standupstage-irc`.
