### ISSUE TITLE
Consider switching to CircleCI

### ISSUE THREAD

**Issue by pmac** [mozilla/standup#202]
Travis is great, but slow. I've had good luck with https://circleci.com/ and the Mozilla org already supports it. Let's discuss whether or not to do this here.

**Comment by willkg** [comment]
I'm game for Circle. I don't have a preference either way.

What would Jonathan Coulton do?

**Comment by pmac** [comment]
I think he might not do this actually. I've just tried circle to deploy another project using docker to Heroku and it failed. Heroku requires a newer version of docker than circle supports. We should stick with Travis for now.
