### ISSUE TITLE
site performance monitoring

### ISSUE THREAD

**Issue by willkg** [mozilla/standup#210]
It'd be nice to have some site performance monitoring like New Relic or Datadog or something so we can see what's going on.

It's not clear whether we *need* this, but it's a nice to have if we plan on any ongoing development/maintenance.

**Comment by pmac** [comment]
I'll ask about glomming onto someone's New Relic. I think it'd be really interesting to see, especially at first so we can know where to throw some cache.

**Comment by pmac** [comment]
I got approval to add this to the Marketing New Relic account. I'll start on this soon if that sounds good.

**Comment by willkg** [comment]
Two things:

1. Sounds good to me!
2. Thank you, Marketing!
