### ISSUE TITLE
user "username", "slug" and irc nicks

### ISSUE THREAD

**Issue by willkg** [mozilla/standup#212]
The Django User model has a `username` field that we're using as the irc nick. There's also a `slug` field on the StandupUser model. This is a bit confusing and should get sorted out.

Maybe something like:

1. add an `irc_nick` field to the `StandupUser`
2. nix the `slug` field altogether since `username` is probably slug-like enough that we can use that for the url to the user page

?

**Comment by willkg** [comment]
Another thing this affects is the `UpdateStatus` API view which is looking up users via irc nick and the username field. Bleh. That should get looked at and possibly fixed, too.

**Comment by willkg** [comment]
Working on this now because I kicked this can down the road and I think it's causing big problems.

**Comment by willkg** [comment]
I read through the code and here's the situation:

`StandupUser.slug`

* When creating a Github auth-based account, this comes from the github login as does `github_handle`.
* Gets used by feed urls.
* Used by user page view.
* Labeled as the "irc nick" in the Profile form.
* Used for the `__repr__` of a StandupUser.
* Used in `htmlify` -- this one is tricky because people are probably writing standup messages from IRC, so they're probably matching IRC nicks.

`django.contrib.auth.models.User.username`

* used by API StatusCreate, StatusDelete, and UpdateUser to match username to StandupUser record (therefore used by irc bot)

**Comment by willkg** [comment]
So I think we have a few problems:

1. IRC nick is tied to `User.username` in the API and `StandupUser.slug` everywhere else, so that's bad. (and my fault)
2. IRC nick being tied to `User.username` or `StandupUser.slug` seems like a bad idea. These three things should really be independent of one another. Maybe I change my irc nick because my online persona changes--does that mean I have to change the url to my user page and my username, too?
3. At some point, we might want to add other services, so adding a new field for every service doesn't scale well. Having said that, I think we should kick that can down the road for now.

Looking at the old code, it did this:

1. the API used `username` for matching IRC nicks.
2. the profile view had a `username` field and the value in that field was saved in both `username` and `slug` in the db.

I think the obvious options are these:

* Option 1: Standardize on `User.username`.
* Option 2: Standardize on `StandupUser.slug`.
* Option 3: Create a new `StandupUser.irc_nick` field.

Are there other options?

I'm inclined to go with option 3. The required changes would be something like this:

1. Write a migration copying `User.username` to a new `StandupUser.irc_nick` field.
2. Fix the factory to populate the irc_nick field.
3. Fix the profile views to use the new `StandupUser.irc_nick` field.
4. Fix the API code to use the new `StandupUser.irc_nick` field.

**Comment by willkg** [comment]
@pmac What do you think? If you're ok with option 3, I'm game for doing that work now. It's probably like a half day of work.

**Comment by pmac** [comment]
I'd be very happy with option 3

**Comment by willkg** [comment]
Option 3 implemented in #269. In doing that, we bumped into a couple of issues. I'll write those out after this lands.

**Comment by willkg** [comment]
I pushed it to -stage, tested it out and then pushed it to -prod. Seems good.

Going to close this out and create issues for the new problems I created.
