### ISSUE TITLE
Implement HTTP Security Headers (XCTO, XFO, XXSSP)

### ISSUE THREAD

**Issue by freddyb** [mozilla/standup#223]
This bug is about implementing basic HTTP security headers.
* `X-Content-Type-Options: nosniff` (also known as XCTO)
* `X-Frame-Options: DENY` (or `SAMEORIGIN`, also known as XFO)
* `X-XSS-Protection` (also known as XXSSP)

Doing so comes at no cost and will certainly not break anything, given how the app currently works.

**Comment by freddyb** [comment]
XFO is #225.
X-XSS-P should be enabled, if I read [this line](https://github.com/mozilla/standup/blob/0c2e1859f7936de00ebaf44d2a0eabb41c399f6b/standup/settings.py#L148) correctly, but it isn't :-(
XCTO is #226

**Comment by pmac** [comment]
These are all done. Thanks!
