### ISSUE TITLE
standup v2 push-to-prod

### ISSUE THREAD

**Issue by willkg** [mozilla/standup#228]
After we've done a system test and worked through any issues that's brought up, we want to push to prod. This issue covers the checklist of things we need to do:

- [x] heroku maintenance mode for web app
- [x] take snapshot of prod database
- [x] turn off standups bot
- [x] deploy standup: tag a commit and push tag to github
- [x] set some admin users via heroku shell
- [x] create new production [github oauth app](https://github.com/settings/developers)
- [x] config prod standup to use github oauth app
- [x] generate new API key 
- [x] deploy standup-irc
- [x] configure standup-irc to use new API key
- [x] start standup-irc and turn off web app maintenance mode
- [x] smoke test
- [ ] add [SSL](https://devcenter.heroku.com/articles/ssl)

**Comment by pmac** [comment]
edited a bit. thoughts?

**Comment by willkg** [comment]
This looks good to me! I didn't even know about some of these items.

I think it's a good idea to do heroku maintenance mode. I didn't know that existed until just now. That's neato!

**Comment by pmac** [comment]
I'mma call this done and we'll follow up on the SSL via #168
