### ISSUE TITLE
user should be able to specify timezone

### ISSUE THREAD

**Issue by willkg** [mozilla/standup#229]
From https://github.com/mozilla/standup/issues/219#issuecomment-248674292

@globau said:

> looking forward to being able to set my timezone :)

**Comment by willkg** [comment]
@globau Just to clarify, you're interested in being able to set your timezone on your user profile. What effects would this have? Is it just to show you all the times on the web-site in your time zone? Would it have other effects?

**Comment by pmac** [comment]
I was thinking about doing this on the client side actually. Just using a relative time JS lib that will read UTC timestamps and display local time. Would that work?

**Comment by globau** [comment]
i'd prefer to have everything to be displayed as per the timezone i set.  this includes ensuring the items are put into the correct date, and any reports are correctly bounded as per my timezone not utc.

client-side only is better than not at all, as long as items are put into the correct date (see #51 and #79).

**Comment by willkg** [comment]
Ok. Sounds like this is just a duplicate of #51. I'm going to close it out then.
