### ISSUE TITLE
add way to do site-wide announcements

### ISSUE THREAD

**Issue by willkg** [mozilla/standup#236]
It'd be really handy to have a way to do site-wide announcements so that we can communicate with Standup users various things like upcoming maintenance windows, incoming meteors, swag, comic books, ...

I've rolled my own in previous projects. It's not a hard thing to implement.

Another alternative is use django-soapbox (https://github.com/ubernostrum/django-soapbox). Pretty sure MDN uses that.

Whatever we do, it'd be super nice to be able to expose messages in any kind of status-check API endpoint, too. That way any non-website client can get status info and alert people who aren't using the website.

**Comment by a2sheppy** [comment]
Yes, MDN uses django-soapbox. I don't know much about how it's implemented, although I will say that the result is decent.
