### ISSUE TITLE
mozilla status board: research

### ISSUE THREAD

**Issue by willkg** [mozilla/standup#237]
Might be interesting to look at another standup-like site at Mozilla for ideas/inspiration/helpful flows/etc:

http://statusupdates.dev.mozaws.net/

https://github.com/bsmedberg/mozilla-weekly-updates

There are two good reasons to do this:
1. We could discover something that's super useful.
2. That board also uses Persona and they're about to be hosed, so maybe joining boards is a viable option.

**Comment by edunham** [comment]
cc @bsmedberg, author and maintainer of statusboard

**Comment by willkg** [comment]
Seems like either no one was interested in this or Standup is good enough that it's at least minimally viable for now. Given that, I'm going to close this out.
