### ISSUE TITLE
Gravatar using HTTP (not HTTPS) causes mixed content warnings

### ISSUE THREAD

**Issue by freddyb** [mozilla/standup#246]
`GRAVATAR_SECURE = True` in settings.py should make them go away.

(I found this by browsing to https://standups.herokuapp.com/)

**Comment by pmac** [comment]
Yup. Just waiting to get the SSL done for the real domain. The [setting is ready to go](https://github.com/mozilla/standup/blob/master/standup/settings.py#L161).
