### ISSUE TITLE
register #standup on irc.mozilla.org

### ISSUE THREAD

**Issue by willkg** [mozilla/standup#247]
I forget who created the channel, but it would have been ages ago. I suspect it's not registered. Regardless, at least @pmac and I (willkg) should have ops access.

This issue covers sorting out #standup on irc.mozilla.org.

**Comment by pmac** [comment]
I'll ask an IRCop to help us out.

**Comment by pmac** [comment]
justdave hooked us up. The channel is now registered and @willkg and I are now auto-op.
