### ISSUE TITLE
upgrade to django 1.8.15

### ISSUE THREAD

**Issue by willkg** [mozilla/standup#252]
There was a security release issued:

https://www.djangoproject.com/weblog/2016/sep/26/security-releases/

We should upgrade to 1.8.15.

Also, it's probably prudent to run piprot (https://pypi.python.org/pypi/piprot) and update other things.

**Comment by willkg** [comment]
@pmac upgraded Django in #251.

I'm going to reduce the scope and close this out.

**Comment by pmac** [comment]
+1 for piprot though.
