### ISSUE TITLE
Can't log in with Github

### ISSUE THREAD

**Issue by mythmon** [mozilla/standup#258]
I'm not sure if this is related to #230 or not, but I can't login with Github after logging in with Persona.

![shot_8996](https://cloud.githubusercontent.com/assets/305049/18895141/23749792-84cc-11e6-8227-ec7b73c9d372.png)

**Comment by edunham** [comment]
Same here, I also get "Authentication failed: The redirect_uri MUST match the registered callback URL for this application." when I try to log in. I have not used standups before and am trying to log in to create an account.

**Comment by pmac** [comment]
Sorry all. I think this broke when we upgraded the site to HTTPS only. The URL the Github Oauth app had was still http. I've now updated the settings. Please try again and let me know if it works again for you. Thanks for reporting.

**Comment by mythmon** [comment]
Now I get further, but when being redirected back to Standups, I get a 500 error. I bet that's the same as #230 though.

**Comment by pmac** [comment]
I do see you in there twice, but the two users have different email addresses, so it should work. I'll keep looking.

**Comment by mythmon** [comment]
That's odd. I don't know why I'd have two users in the system

**Comment by willkg** [comment]
I'm going to close this out since this specific issue is solved now.

The "I try to log in and get an HTTP 500" issue will get covered with #230.
