### ISSUE TITLE
http 404 for https://standupstage.herokuapp.com/login/undefined/

### ISSUE THREAD

**Issue by willkg** [mozilla/standup#263]
Reported via IRC by @Callek:

```
<Callek> it had "Callek|Buildduty" as my nickname, tried to change to "Callek" and got 
"denied, user with slug already exists" -- I tried logging in with my Callek@gmail.com 
community login and got a 404/undefined page instead too :(
...
<willkg> what's the url for th 404 page?
<Callek> https://standupstage.herokuapp.com/login/undefined/
```

**Comment by hiikezoe** [comment]
I am seeing a similar error when I tried to login via Persona.  The url is https://www.standu.ps/login/undefined/

Also I can't login via github account too.  The error message is 'You must be signed in to view your profile. Please sign in and try again.'.

**Comment by willkg** [comment]
None of us are around this week. On Monday, ping me on IRC and we can sort this out. I'm willkg.

**Comment by willkg** [comment]
I just pushed out changes that ditch Persona and Github auth in favor of Auth0 which lets you use Github to authenticate or a passwordless email code.

Can you try that out and see if you can log in? If you have any problems, let me know.

**Comment by willkg** [comment]
I think the problems in this issue are covered in other issues and we're all set here. I'm going to close it out.
