### ISSUE TITLE
standup statistics page

### ISSUE THREAD

**Issue by willkg** [mozilla/standup#267]
It'd be nice to have a page that lists standup statistics for the last week:
- active users
- total number of new standup posts
- tags used?
- total number of posts by project?
- total number of posts by team?

Maybe make this report generated and saved in the db? This will make it easier to see things over time plus we can (ab)use this to contact people about upcoming changes and their usage patterns.

**Comment by willkg** [comment]
If we had a fetch API endpoint, we could also generate this externally. That's probably a good way to start this off.

**Comment by a2sheppy** [comment]
If this could be filtered by user, team, and/or project, that could be a potentially powerful tool for monitoring progress on work being done.
