### ISSUE TITLE
fix auth to allow for easier development

### ISSUE THREAD

**Issue by willkg** [mozilla/standup#268]
Right now if you want to do local development, you have to use Persona auth because that doesn't require tokens. If you want to use GitHub auth, you have to set up tokens and blah blah blah.

When Persona goes away, we should have some kind of fake-GitHub auth working so someone can spin up a docker environment, create an account and be good to go.

**Comment by willkg** [comment]
If there's a way to do this already, then we should document it and adjust the defaults accordingly.

**Comment by pmac** [comment]
We can possibly just document `use ./manage.py createsuperuser` and have that be it, though setting up a github auth app should probably be documented as well.

**Comment by willkg** [comment]
That doesn't log you in, though. We need something that logs you in.

**Comment by pmac** [comment]
I believe the admin login form is still there. going to /admin/ while not logged in should get you a username/password form.

**Comment by willkg** [comment]
Oh, funky. So to clarify, you're saying:

1. I'm a dev and I do `make build` in my docker environment.
2. Then I do `docker-compose run web ./manage.py createsuperuser` to create an admin user.
3. Then I can go to `/admin/`, log in and that logs me into the site just like using GitHub auth would.

Is that right? If so, I want to tweak some of those bits to streamline them and then document that so I don't forget. Probably create a `make createuser` rule which spits out instructions on how to log in with that user or something along those lines.

**Comment by pmac** [comment]
That should be right. I just tested it and something is wrong w/ that login. It should work though. I'll try to get it working again. Problem might be in my config.

**Comment by willkg** [comment]
This is old and predates our auth0 implementation. That's fine. However, issue #354 covers local development, too, and I think that one is more relevant to our current architecture.

Given that, I'm going to close this one out.
