### ISSUE TITLE
organize a sprint in Hawaii?

### ISSUE THREAD

**Issue by willkg** [mozilla/standup#281]
A bunch of us will be in Hawaii. Should we organize a Standup sprint? If so, what do people want to work on?

**Comment by pmac** [comment]
We need to really fix identity and possibly more about auth. I hear that much of Mozilla will be moving to auth0. I should know more about that before #Mozhalo from other projects. Hopefully Standup can glom on and we can sprint on adding that auth method.

**Comment by willkg** [comment]
How about these possible sprint themes?:

1. fixing teams and team maintenance
2. nixing `reply_to` and replacing with cheers?
3. fixing IRC-behavior issues with standup-irc
4. API: user API tokens and expanding the API so it can be used for other clients
5. statistics pages and better team/project/week breakdown pages

**Comment by willkg** [comment]
@bsmedberg sent us an email earlier today. The following might be good things to work on as well:

1. weekly email rollups
2. ability to have one standup update apply to multiple projects (there's a lot of complexities in this especially around linking github PRs)

Plus we might need a better web-form for creating standup updates--bigger box, explanation of valid markup, list of recently used projects/tags for that user, ability to see last standup update, etc.

**Comment by willkg** [comment]
@pmac and I met and worked through the auth plan. We're going to switch to auth0 which solves a bunch of problems Standup users either have or were concerned with. Plus that'll reduce the code required.

I started working on #295 and requested an auth0 thing for standup -stage.

**Comment by willkg** [comment]
We didn't end up doing a sprint in Hawaii. No one seemed particularly interested and/or no one knew about it.

I'll write up a new issue for the upcoming San Francisco All Hands and make sure to do better messaging. Maybe stickers.
