### ISSUE TITLE
Getting a 500 error trying to link standup with my Github account

### ISSUE THREAD

**Issue by n1k0** [mozilla/standup#297]
Trying to authorize the app with my Github account, I'm getting this page:

![](http://i.imgur.com/koSZsus.png)

The partially obfuscated URL of this page is `https://www.standu.ps/complete/github/?code=<snip>&redirect_state=<snip>`.

The app is listed as an authorized app in my Github settings. I've tried to revoke/reauthorize with no success.

**Comment by willkg** [comment]
I can see the crash data in Sentry. I've seen this before--pretty sure it's a bug in our github flow.

I'll take a look at the data in the db and let you know.

**Comment by willkg** [comment]
Seems like you've got an account and it's just not completing the login. Can you try going to https://www.standu.ps/ and see if you're logged in now?

As an aside, last week we decided to switch to auth0, so this will all likely change soon.

**Comment by n1k0** [comment]
> Seems like you've got an account

That's something I forgot to mention, indeed I had an account I didn't use for years.

> Can you try going to https://www.standu.ps/ and see if you're logged in now?

I've just tried, I'm still getting the same 500 error.

> As an aside, last week we decided to switch to auth0, so this will all likely change soon.

I may just wait then.

**Comment by willkg** [comment]
I just pushed out changes that ditch Persona and Github auth in favor of Auth0 which lets you use Github to authenticate or a passwordless email code.

Can you try that out and see if you can log in? If you have any problems, let me know.

**Comment by n1k0** [comment]
> Can you try that out and see if you can log in? If you have any problems, let me know.

So I could successfully register with my mozilla address using auth0, though trying to use the github auth didn't work as well. Problem solved still I think.

On the other hand the IRC bot links my status update page at [www.standu.ps/user/NiKo`/](https://www.standu.ps/user/NiKo`/), which is 404, though my status updates are properly saved. I'll file a separate issue about this.

**Comment by willkg** [comment]
I'm in the process of fixing/improving/rewriting the auth0 support. After that, I can help with fixing accounts. Really sorry about that--it's been tough.

**Comment by willkg** [comment]
I pushed the Auth0 rewrite just now.

You've currently got two accounts. All the status posts are tied to the mozilla.com address. Your Github account is tied to a different email address, so going forward you'll need to use passwordless email or Mozilla LDAP providers to log into the site.

I think this is all set--the other problems are covered in other issues. I'm going to close this out.

If you still have problems, please let me know.
