### ISSUE TITLE
Add me to the Servo project

### ISSUE THREAD

**Issue by jdm** [mozilla/standup#300]
I do my updates all at once from the website, and I assume that's why I am not considered part of the Servo project. Could I be added to it?

**Comment by willkg** [comment]
Anyone can post to any project--you don't have to "belong" to a project.

If you want to post a status update for a specific project, you need to post the status update from the related IRC channel or the project page.

For example, if you want to post to the Servo project, you either post from the `#servo` irc channel or the servo project page here: https://www.standu.ps/project/servo/

Hope that helps!
