### ISSUE TITLE
User page is 404 when username contains a backtick (`) 

### ISSUE THREAD

**Issue by n1k0** [mozilla/standup#312]
My IRC nickname is *NiKo`* (notice the backtick at the end) and it seems the system doesn't accept this char in the urls, so my page is 404 : https://www.standu.ps/user/NiKo%60/

Also and as a probable side effect, my entries are not linked to my personal profile page but to [the team's one](https://www.standu.ps/project/storage-team/) (though maybe that's a setting? idk).

Feels like some regex needs to be updated anyway. (Edit: #313)

**Comment by willkg** [comment]
@n1k0 Where did you get that url from?

**Comment by n1k0** [comment]
From the IRC bot in irc.mozilla.org#storage-team

**Comment by willkg** [comment]
Ahh... Ok. That's this bug: https://github.com/mozilla/standup/issues/279

I'm going to close this out because fixing that fixes the original issue here before we got deep into the woods regarding backticks in slugs.
