### ISSUE TITLE
Can't log in, can't create account

### ISSUE THREAD

**Issue by jdm** [mozilla/standup#315]
I had an account on the pre-auth0 standups. Now when I tried to log in using auth0 via github, it brought me to the account creation page, and when I entered `jdm` as my nick it said a user already existed. There doesn't appear to be a way to log in with my previous account; I only have the option to create a new account when use my email address instead of github.

**Comment by willkg** [comment]
I'm in the process of fixing/improving/rewriting the auth0 support. After that, I can help with fixing accounts. Really sorry about that--it's been tough.

**Comment by willkg** [comment]
@jdm I merged the new account into the old account. I think it should work now.

Can you check it out by logging into Standup using the Github provider and let me know what happens?

**Comment by jdm** [comment]
I was able to log in! Thanks!
