### ISSUE TITLE
markdown links with hashes in link text get corrupted

### ISSUE THREAD

**Issue by froydnj** [mozilla/standup#321]
In writing my most recent status update, I wrote:

```
[#3510](https://github.com/rust-lang/cargo/pull/3510)
```

which I expected to get linkified like: [#3510](https://github.com/rust-lang/cargo/pull/3510)

Instead, it got linkified as shown in [my status update](https://www.standu.ps/status/40927/) (the "`cargo` test fixes" bullet), which...I'm not quite sure if there's a better way to describe it than looking at the result.

I assume this is a result of the `#` character in the link text, but I'm not really sure...

**Comment by pmac** [comment]
Thanks for reporting. I thought I saw something like this before but then couldn't find it again. I'll see about figuring this out now.

**Comment by pmac** [comment]
Autoclosed from merge, but this is not yet in prod. I'll test on stage shortly and this will hopefully roll out to prod soon. Thanks again.

**Comment by pmac** [comment]
It seems to work on [stage](https://standupstage.herokuapp.com/status/38215/). We can't push this to prod yet because we're still working on some issues with authentication, but this will go out with that stuff. Feel free to test on stage and update this issue with any other linking strangeness.
