### ISSUE TITLE
Create a team for Japan engineers

### ISSUE THREAD

**Issue by birtles** [mozilla/standup#324]
Hi, I'd like to add a team for Japan engineers (called just "Japan"?) including the following members:

  * Masayuki Nakano - masayuki-nakano
  * Makoto Kato - makotokato
  * Hiroyuki Ikezoe - hiikezoe
  * Daisuke Akatsuka - dadaa
  * Mantaroh Yoshinaga - mantaroh
  * Brian Birtles - birtles

**Comment by willkg** [comment]
Team is created:

https://www.standu.ps/team/japan/

Everyone has been added to the group.

Let me know if you have any problems!

**Comment by birtles** [comment]
Thank you!
