### ISSUE TITLE
caching failures

### ISSUE THREAD

**Issue by willkg** [mozilla/standup#334]
Standup -stage has caching enabled and using the Memcachier Heroku addon. However, we're seeing this in the logs:

```
2017-01-18T22:20:04.755231+00:00 app[web.1]: [18/Jan/2017 22:20:04] ERROR django.pylibmc:
MemcachedError: error 40 from memcached_get(:1:views.decorators.cache.cache_): (0x2dd1650)
FAILED TO SEND AUTHENTICATION TO SERVER, no mechanism available,  host: xxx:11211 ->
libmemcached/sasl.cc:238
```

Looking at the Memcachier dashboard, we see 0mb is used in the cache. I think both of these observations suggests that it's not working.

This issue covers fixing that.

**Comment by willkg** [comment]
Today we looked at the configuration and though we didn't see any obvious issues, we redid our configuration based on the Memcachier docs:

https://devcenter.heroku.com/articles/memcachier#django

That didn't change anything.

Some searching found this:

* https://github.com/heroku/heroku-buildpack-python/issues/201
* http://stackoverflow.com/questions/27837326/memcachier-add-on-for-cloudcontrol-is-failing

That suggests maybe the problem is with our libmemcached.

@pmac tried switching from the packaged version of pylibmc to one we built ourselves during the deploy and that didn't change anything, either.

I think the next step is to look at building libmemcached. Maybe we've got an old version? Maybe the version we've got is bad in some way? Something like that.

**Comment by willkg** [comment]
I spent some more time with it just now. Seems like we're hitting this:

https://bugs.launchpad.net/ubuntu/+source/libmemcached/+bug/1573594

I don't understand how this seems like a big deal, but there's like zip when doing a search for the error string on Google.

Anyhow, I think we have the following things we could try:

1. Switch to python-memcache pure python lib. It might not support auth and thus memcachier.
2. Switch to a different memcache service on Heroku.
3. Isolate this into a smaller project so we can debug/tinker with it more easily--should be straight-forward.
4. Run memcached in the container with our code. (@willkg isn't enthused about this option.)
5. Give up and switch to the db caching backend.

I'll try the first two tomorrow.

**Comment by pmac** [comment]
We could also try redis as a cache server. That protocol is well supported and Heroku has an official plugin for it. Looks like neither an external memcache nor redis would be a secure place to store anything sensitive though.

https://devcenter.heroku.com/articles/securing-heroku-redis

**Comment by willkg** [comment]
We're going to make a bunch of changes:

1. ditch cache-backed sessions
2. ditch page caching--we probably don't need it at our scale anyhow
3. move the auth0 `id_token` renewal thing to the session
4. switch back to locmem and drop memcachier--with the above changes, we'll no longer need a shared cache

Working on that now.

**Comment by willkg** [comment]
Reminding myself that after PR #336 lands, we need to nix the memcachier addon.

**Comment by willkg** [comment]
I removed the memcachier addon and landed all this stuff and our caching problems are gone now!
