### ISSUE TITLE
drop our auth0 implementation and switch to mozilla-django-oidc

### ISSUE THREAD

**Issue by willkg** [mozilla/standup#345]
I didn't really understand what what we were implementing was an oidc client. Now that that's clearer, we should look at dropping our 1600 lines of auth0 stuff in favor of libraries.

This set looks promising:

* https://pypi.python.org/pypi/oic/0.9.4.0
* https://pypi.python.org/pypi/django-oidc/0.1.4

Maybe this one?:

* https://pypi.python.org/pypi/django-auth-oidc/0.1.0

**Comment by willkg** [comment]
Scratch all that.

I've been spending some quality time with mozilla-django-oidc (https://github.com/mozilla/mozilla-django-oidc/). I've been improving the documentation, pouring over the code and tests and improving that, and making sure it reflects everything I bumped into when making the auth0 thing that Standup is currently using.

I have some more work to do, but then we're going to switch to that.

Rough plan:

1. finish up work on mozilla-django-oidc
2. make code changes which involve a database migration to drop the auth0 tables we have
3. talk with IAM to update the callback url for Standup -stage environment, deploy, test, and verify
4. talk with IAM to update the callback url for Standup -prod environment, deploy, test, and verify

It's possible we have to update more than just the callback url--I'll know more when we update -stage.

**Comment by willkg** [comment]
Grabbing this to work on in May some time.

**Comment by willkg** [comment]
I got a standup -dev set of credentials for the Mozilla SSO and have been toying with the master tip of mozilla-django-oidc.

Things that are working:

1. log in with an existing user
2. update profile information

Things that aren't working:

1. log out
2. id token renewal (happens via the middleware)
3. new user flow

Getting there.

**Comment by willkg** [comment]
I got everything working. Feels a little squirrel y, but it's good enough and lets us drop like 1700 lines of code which is good. Yay.

I'm going to keep working on mozilla-django-oidc and get them to do a release, then we'll switch to that. It'll require us to change some settings, but otherwise it shouldn't affect anything and users shouldn't notice.

**Comment by pmac** [comment]
This is wonderful! Thanks @willkg!! 💯
