### ISSUE TITLE
Rename me

### ISSUE THREAD

**Issue by nox** [mozilla/standup#348]
For some reason, my name is "nox" and my handle is "@ Anthony Ramine" on standups, could that be reversed please?

**Comment by willkg** [comment]
On the profile page, you should be able to fix your name. The username and slug can't be changed on the profile page, so I'll switch both of those to nox.

Let me know if that works.

**Comment by willkg** [comment]
Also, can you walk me through what you did to create a new account? Which system did you use to authenticate (github, email, ldap)? Did you make changes to your profile page afterwards?

**Comment by nox** [comment]
I logged in today with my LDAP account, set my name to "Anthony Ramine" and everything else (i.e. IRC handle and Github handle) to "nox". It displayed as "nox / @ Anthony Ramine", the opposite of what I expected. I then changed everything to "nox" in my profile page to see what would happen, but it stayed as "nox / @ Anthony Ramine".

**Comment by willkg** [comment]
I think you're all set now, but I'm not sure. I made a bunch of changes over the last week to the db and the profile page and fixed some bugs in Standup all possibly related to what you were seeing.

Can you try logging in again with your LDAP account and check the data? If it's wrong, are you able to fix it on the profile page? If not, let me know.

**Comment by nox** [comment]
Seems ok now. Out of curiosity, how do I change my picture?

**Comment by willkg** [comment]
Awesome! Thanks for letting me know.

The profile picture is from gravatar and is based on your email address.

Hope that helps!
