### ISSUE TITLE
Please merge my account @hiikezoe and @hiikezoe2

### ISSUE THREAD

**Issue by hiikezoe** [mozilla/standup#350]
I have an account named @hiikezoe already.  When I logged in standup.ps with mozilla LDAP via website, I did accidentally create a new account named @hiikezoe2. 
Please merge those account into the old one.  I guess the email account of the old one is hiikezoe@mozilla-japan.org.  Now the address has been discarded, I am using hikezoe@mozilla.com.

Thank you,

**Comment by willkg** [comment]
This should be all set now. Let me know if you have problems. Thank you!

**Comment by hiikezoe** [comment]
Confirmed that I can login via hikezoe@mozilla.com LDAP as @hiikezoe. Thank you!
