### ISSUE TITLE
standups' success replies should (optionally?) be sent via PM rather than in the channel

### ISSUE THREAD

**Issue by mhammond** [mozilla/standup#376]
One barrier to people feeling comfortable with using standups in IRC is the additional noise it creates in the channel - standups often replies with "Ok, submitted ..." - so double the "noise" the status report itself creates.

This reply is only valuable to the person submitting the request - other people in the channel probably see value in the initial status report, but not in that second response from standups. It seems it might be better delivered via PM. Error and other unexpected responses going to the channel might make sense.

**Comment by willkg** [comment]
You say "One barrier to people feeling comfortable with using standups". We've revised the reply a couple of times based on peoples' needs, but I've not heard of this being a barrier to people using Standups before. I'm curious how prevalent the feeling is.

Can you talk more about this? Is it related to culture on your project/channel/team? Have you been involved in discussions about this? Can you point me to them?

**Comment by mhammond** [comment]
I guess it would be better described as an anecdote - when talking to a couple of people in my team, they expressed a preference for adding updates via the web interface as they feel the additional noise in the channel isn't worthwhile. I guessed that halving the amount of noise per update might help address their concerns.

**Comment by willkg** [comment]
That makes sense.

Also, I screwed up. The IRC client has this already. It's the talkback setting and it can be set on a channel-by-channel basis.

So you should be able to do:

```
standup: !talkback quiet
```

and it'll stop replying to status posts in that channel.

Hope that helps!

**Comment by willkg** [comment]
I'll add a note to the FAQ about that.

**Comment by mhammond** [comment]
It does, thanks!
