### ISSUE TITLE
Help merging two accounts

### ISSUE THREAD

**Issue by m-branson** [mozilla/standup#380]
Looks like I need to merge my Standu.ps accounts. Logged in via SSO and inadvertently made a new account with my new LDAP email.

Current account w/correct username for Standu.ps: hello@meganbranson.com
New account with LDAP email, but wrong username: mbranson@mozilla.com

Can we merge these accounts, using my LDAP email and keeping my user name of @mbranson?

Thanks!

**Comment by willkg** [comment]
Sorry about that. I saw this earlier today, meant to do it then, then forgot.

It's done now. Let me know if that helped!

**Comment by m-branson** [comment]
Awesome, looks great! Thanks @willkg

**Comment by willkg** [comment]
Yay!
