### ISSUE TITLE
Create a team for Participation Systems

### ISSUE THREAD

**Issue by comzeradd** [mozilla/standup#393]
Hi,

We need a new team for Participation Systems.

Members:

* [leo](https://www.standu.ps/user/leo/)
* [nemo-yiannis](https://www.standu.ps/user/nemo-yiannis/)
* [yalam96](https://www.standu.ps/user/yousef/)
* [comzeradd](https://www.standu.ps/user/comzeradd/)
* [viorelaioia](https://www.standu.ps/user/viorelaioia/)
* [hmitsch](https://www.standu.ps/user/hmitsch/)
* [mbranson](https://www.standu.ps/user/mbranson/)
* [tasos](https://www.standu.ps/user/tasos/)

Thanks

**Comment by willkg** [comment]
https://www.standu.ps/team/parsys/

Let me know if that works and/or if I got anything wrong.

**Comment by comzeradd** [comment]
Everything looks good. Thanks 👍
