### ISSUE TITLE
add pyup or something like that

### ISSUE THREAD

**Issue by willkg** [mozilla/standup#399]
I just did a massive requirements update. This project is pretty "back-burner" for me, so I'm thinking it behooves us to set up pyup and have it submit PRs once a week or once a month plus security updates.

Another alternative is requires.io. There are probably others. I don't really have an opinion which one we pick.

Does that sound like a good idea?

**Comment by pmac** [comment]
+1 for pyup.io. I've not used it before but have been meaning to. It's come highly recommended.

**Comment by willkg** [comment]
I added pyup to Standup. PR #402 fixes the configuration file.

**Comment by willkg** [comment]
We've got pyup in place and it did an initial requirements update pass. I'm going to close this out.
