### ISSUE TITLE
Please remove the mhommey user

### ISSUE THREAD

**Issue by glandium** [mozilla/standup#422]
I accidentally "created" (and posted with) the user mhommey (at mozilla.com) because I logged in with the wrong thing (mozilla account instead of github account).

**Comment by willkg** [comment]
No worries! This happens semi-regularly even with me. It's frustrating--I wish we could figure out a better UX to alleviate the likelihood this happens.

I merged the mozilla.com one into the github one just now.

Let me know if that worked.

**Comment by glandium** [comment]
It seems to have worked, thanks.

**Comment by glandium** [comment]
Can you remove the @mhmozilla user? It was created because I logged in via email through auth0 for a different service, and that spilled to standups...

**Comment by willkg** [comment]
Sorry it took so long to get to this. You should be all set now!

I opened up #425 to deal with the underlying problem that makes this happen.
