### ISSUE TITLE
Please change nnethercote's account to use LDAP instead of GitHub

### ISSUE THREAD

**Issue by nnethercote** [mozilla/standup#431]
I file a standu.ps report once a week. Between each time I inevitably log into something with LDAP, which always causes standu.ps to want to use an LDAP login, which takes me to an nnethercote2 account. I now know that I need to logout and re-login using my GitHub creds to get to my nnethercote account, but it would be nice if I could avoid that step.

If my nnethercote account could be changed to use LDAP creds I think that would solve my problem. (I don't think I can make that change myself via my profile.)

Thank you.

**Comment by willkg** [comment]
This is super frustrating--I'm really sorry. Issue #425 will alleviate the problem, but no one has worked on it, yet. @pmac and I have been busy and no one else wants to work on Standups.

I switched your account to your LDAP email address. I think you're right on in that this will also fix your problem.

Let me know if that works!

**Comment by nnethercote** [comment]
I logged out and logged back in with LDAP and it appears to be working. Thank you.

**Comment by willkg** [comment]
Awesome! Closing this out accordingly.
