### ISSUE TITLE
Please change arai's LDAP account

### ISSUE THREAD

**Issue by arai-a** [mozilla/standup#438]
I'm using standu.ps account https://www.standu.ps/user/arai/ with LDAP account arai_a@mac.com (volunteer contributor account).
I'd like to switch to LDAP account tfujisawa@mozilla.com (MoCo account), while keeping the standu.ps account name (arai) and its history.
Thanks!

**Comment by willkg** [comment]
I merged the new standups account into the old one. The resulting standups account has the mozilla.com identity.

You'll probably need to log out and back in again. After that, you should be all set.

If you hit any problems, let me know!
