### ISSUE TITLE
Please merge the ferjm and ferjm_ users

### ISSUE THREAD

**Issue by ferjm** [mozilla/standup#452]
Apparently I used standu.ps with Github and my LDAP accounts. It would be great if both accounts could be merged. Thank you!

**Comment by willkg** [comment]
If you have an LDAP account, we need to merge the GitHub one into the LDAP one, so you'd log in with your LDAP one going forward.

I did that. You should be all set! Let me know if you have any problems!

**Comment by ferjm** [comment]
Thank you!
