### ISSUE TITLE
Can I take over the Paul account?

### ISSUE THREAD

**Issue by paulrouget** [mozilla/standup#454]
It doesn't appear to be used. Not sure if I opened this account a while ago or if someone else use it.

**Comment by willkg** [comment]
When you say "the paul account", do you mean this one?: https://www.standu.ps/user/paul/

**Comment by paulrouget** [comment]
Yes.

**Comment by willkg** [comment]
@pmac Judging by the associated email address, the "paul" account is yours. So I'm going to pass this issue to you to do with as you please.

**Comment by pmac** [comment]
Interesting. I do not remember doing that. Doesn't look to have been used by me or anyone else for status updates. It's fine with me to let @paulrouget have it. Shall we just delete it and let him create it?

**Comment by paulrouget** [comment]
@willkg can you merge `@paulr` into `@paul`, or delete `@paul` or move `@paulr` to `@paul`, whatever is easier for you.

And as we're at it, can you add me to the `servo` team?

Thank you :)

**Comment by paulrouget** [comment]
@pmac @willkg ping?

**Comment by pmac** [comment]
Apologies for the delay. Work has been busy and this is a volunteer run project. I'll see if I can get this done today.

**Comment by pmac** [comment]
I believe this is done. I deleted the old `paul` user and changed your user slug from `paulr` to `paul`. Let me know here if you see any issues.
