### ISSUE TITLE
Invalid certificate on https://www.standu.ps/

### ISSUE THREAD

**Issue by SimonSapin** [mozilla/standup#475]
> www.standu.ps uses an invalid security certificate. The certificate is not trusted because it is self-signed. The certificate is only valid for a6e62d9d7fe4d468ea59fb687e0434a8.71c1fe7be25f142287420f5517abdbf4.traefik.default. The certificate expired on 29 August 2018, 05:33:02 GMT+2. The current time is 29 August 2018, 15:29. Error code: MOZILLA_PKIX_ERROR_SELF_SIGNED_CERT

Possibly linked, the IRC bot currently responds with `Uh oh, something went wrong.` to most commands.

**Comment by pmac** [comment]
This appears to be related to some DNS changes made by Mozilla IT yesterday. We’re working with them to resolve it. Thanks for the report.

**Comment by SimonSapin** [comment]
This appears to be fixed now, thanks!
