### ISSUE TITLE
Implement API to extract data

### ISSUE THREAD

**Issue by Ms2ger** [mozilla/standup#478]
Apparently the API that existed to extract data disappeared in a rewrite some time ago. It would be valuable to implement a simple one before decommissioning.

@simonsapin: I guess you might be interested as well

**Comment by SimonSapin** [comment]
In my case I’ve consistently entered data through IRC, so I’ve decided that the easiest way to extract my data is from IRC logs. But yes, if someone wants to build an API that returns for example everything for a given user in a big JSON (ideally without pagination), I’d be interested in using it.

**Comment by a2sheppy** [comment]
I would be happy to see this, since I need this information.

**Comment by pmac** [comment]
There is now a JSON endpoint per user. e.g.

https://www.standu.ps/user/pmac.json

This will give you a json blob of all statuses for the user. Please let me know if you get errors as I'm not sure how many statuses this will handle.

**Comment by a2sheppy** [comment]
WFM with 5157 entries.
