### ISSUE TITLE
Get a list of statuses that include a given hashtag

### ISSUE THREAD

**Issue by a2sheppy** [mozilla/standup#76]
It would be really useful to be able to see a page showing all statuses with a given hashtag. Like https://http://standu.ps/hashtag/mfbt to see all posts with the tag #mfbt in them.

This would be particularly useful so we could look for sub-project information, for example.

**Comment by willkg** [comment]
We can do this with the search that we just added (#164)  since tags are just text in the content. Given that, I'm going to mark this as FIXED.

**Comment by a2sheppy** [comment]
This isn't really fixed though -- if you search for "#mdn", you get results for both "#mdn" and "#mdndev"; or is there a magic flag to require exact-match/whole word searches?

**Comment by willkg** [comment]
Mmm... So I claim it's implemented as requested in the summary and description. It's not really possible for me to sit down and think of all possible variations of enhancement requests and guess at all the requirements, so I think the best model here is that we implement what was actually asked for and if that's not sufficient, we open up new issues covering the new requirements.

**Comment by a2sheppy** [comment]
It's just that it didn't get implemented as requested, since the request was specifically to match a given hashtag, not to do general search. ;)

But I'll create a new issue so we don't have to reopen this one. :)
